plot_filename: 'grid_diag_out.png'

height: 800
width: 1200
font_size: 20

var_name: 'hist_APCP_00_L0_PWAT_L0'

title:
xaxis_title:
yaxis_title:

normalize_to_pdf: True

pdf_min: 0.0
pdf_max: 0.001


