plot_filename: 'prob_dist.png'

height: 800
width: 1200
font_size: 20

var_name: 'hist_x_y'

title: 'Probability Distribution Function'
xaxis_title: 'x'
yaxis_title: 'y'

normalize_to_pdf: True

pdf_min: 0.0
pdf_max: 0.1
