plot_filename: hovmoeller.png
height: 400
width: 600
title: Hovmoeller Plot

xaxis:
  x: 180
  y: 0
  title:
    text: Longitude

yaxis:
  x: 0
  y: 0
  title:
    text: Time

date_start: 2016-01-01
date_end: 2016-03-31

lat_max: 5
lat_min: -5

source: ERAI

var_name: precip
var_units: mm / day
unit_conversion: 250

contour_min: 0.2
contour_max: 1.6
contour_del: 0.2
