---
# Values specific to line plot
title: Line plot of point data
connect_data_gaps: true
xaxis:
  title: x-values
yaxis:
  title: y-values
lines:
  - name: Line 1
    data_file: ./line1_plot_data.txt
    color: black
    width: 1
    dash:

  - name: Line 2
    data_file: ./line2_plot_data.txt
    color: black
    width: 1
    dash:
